### ISSUE TITLE
data request

### ISSUE THREAD

**Issue by QiangShiPKU** [ventolab/UHCA#1]
Hi, the corresponding paper (PMID: 34857954) built single-cell and spatial reference maps of the human adult uterus. I want to download the dataset, but get in trouble. Specifically, I found both "Endometrium" and "Endometrium Epithelial" are linked to the epithelial dataset. So, how could get all data of Endometrium?
https://www.reproductivecellatlas.org/non-pregnant-uterus.html

**Comment by luzgaral** [comment]
Dear Qiang,

Apologies & thank you for noticing. It should be fixed now.
https://cellgeni.cog.sanger.ac.uk/vento/reproductivecellatlas/endometrium_all.h5ad

Alternatively, you will find the links to the raw sequencing data in the "[Data availability](https://www.nature.com/articles/s41588-021-00972-2#data-availability)" statement of the paper.

Best,

Luz
